name: Deploy to Prod VPS

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy repository contents to remote server via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          source: "."
          target: "/root/prod"

      - name: Backup Database
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            backup_filename="/root/saves/prod_$(date +'%d_%m_%Y_%H_%M').sql"
            docker compose exec mariadb mariadb-dump -u root --password=${{ secrets.DB_PROD_PASSWORD }} rc_can_app > "$backup_filename"


      - name: Executing remote command via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
                cd /root/prod && git pull origin prod
                docker compose stop
                docker system prune -f
                docker compose up -d
                docker compose exec mariadb mariadb -u root --password=${{ secrets.DB_PROD_PASSWORD }} -e "SELECT 1;"
                docker compose exec php-fpm composer install
                cd .. && chmod 777 -R prod
                cd /root/
                docker compose exec php-fpm php artisan migrate --force
                docker compose exec php-fpm php artisan db:seed --force